// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbjmklhvrmecawaacqeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdiam1rbGh2cm1lY2F3YWFjcWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTY1MjQsImV4cCI6MjA2NzQ5MjUyNH0.VBKg2xl8C7m6VdNcZXCOZ5aGSOnMxuHTDGsJso1sNr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});